### ISSUE TITLE
Property 'self.realm' not initialized at super.init call

### ISSUE THREAD

**Issue by QKai0314** [wrench0318/TodoList_iOS#1]
I write a project like yours, but I don't know how to fix the error. Could you help to fix it? 
It's the project url.
https://github.com/QKai0314/FunChat

**Comment by mdobashi0318** [comment]
I'm sorry I don't seem to be able to help you

However, it seems that the error will be solved if you correct it like this

`
 required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
`

**Comment by QKai0314** [comment]
Thank for your help, I have solved the problem.
